# Generated by Django 5.2.16 on 2026-07-24 02:21

import django.db.models.deletion
import django.utils.timezone
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email invitado"),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=secrets.token_urlsafe,
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="enviada el"),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="canjeada el"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="expira el"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creada el"
                    ),
                ),
                (
                    "consumed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_consumed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="canjeada por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitación",
                "verbose_name_plural": "invitaciones",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("consumed_by__isnull", True)),
                        fields=("email",),
                        name="unique_pending_invitation_per_email",
                    )
                ],
            },
        ),
    ]
