# Generated by Django 5.2.16 on 2026-07-17 06:34

import apps.contributions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField(unique=True)),
                ("built_at", models.DateTimeField(auto_now_add=True)),
                (
                    "criteria",
                    models.JSONField(default=apps.contributions.models._default_criteria),
                ),
                ("min_sample_met", models.BooleanField(default=False)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "pipeline_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
            ],
            options={
                "verbose_name": "versión de dataset",
                "verbose_name_plural": "versiones de dataset",
                "ordering": ("-number",),
            },
        ),
        migrations.CreateModel(
            name="DataContributionConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[("community_dataset", "Dataset comunitario")],
                        max_length=64,
                    ),
                ),
                ("consent_text_version", models.CharField(max_length=32)),
                ("granted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contribution_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "consentimiento de contribución",
                "verbose_name_plural": "consentimientos de contribución",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="contributio_user_id_d7fc6e_idx",
                    ),
                    models.Index(
                        fields=["scope", "is_active"],
                        name="contributio_scope_693ae5_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "scope"), name="uq_consent_user_scope")
                ],
            },
        ),
    ]
