# Generated by Django 5.2.16 on 2026-07-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contributions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetversion",
            name="anonymized_rows",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
