# Generated by Django 5.2.16 on 2026-07-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contributions", "0002_datasetversion_anonymized_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetversion",
            name="consent_text_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="datasetversion",
            name="moderated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datasetversion",
            name="moderation_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="datasetversion",
            name="publication_status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("public", "Público"),
                    ("quarantined", "Cuarentena"),
                    ("retracted", "Retractado"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
