"""Datos estáticos del modelo de DPS/TDO para Pokémon GO.

Fuentes:
  - Type chart: datamining confirmado (Bulbapedia, Game Master).
  - Stats base: Game Master v0.295+.
  - Moves: Game Master v0.295+ (PvE stats).

Convenciones:
  - Tipos en inglés (minúscula) para compatibilidad con el schema del engine.
  - Stats base sin IV (el cálculo los añade según nivel).
  - Moves: power=0 indica move sin daño (p.ej. Splash).
"""

from dataclasses import dataclass
from enum import Enum


class PokemonType(Enum):
    NORMAL = "normal"
    FIRE = "fire"
    WATER = "water"
    GRASS = "grass"
    ELECTRIC = "electric"
    ICE = "ice"
    FIGHTING = "fighting"
    POISON = "poison"
    GROUND = "ground"
    FLYING = "flying"
    PSYCHIC = "psychic"
    BUG = "bug"
    ROCK = "rock"
    GHOST = "ghost"
    DRAGON = "dragon"
    DARK = "dark"
    STEEL = "steel"
    FAIRY = "fairy"


TYPE_COLORS: dict[PokemonType, str] = {
    PokemonType.NORMAL: "#A8A77A",
    PokemonType.FIRE: "#EE8130",
    PokemonType.WATER: "#6390F0",
    PokemonType.GRASS: "#7AC74C",
    PokemonType.ELECTRIC: "#F7D02C",
    PokemonType.ICE: "#96D9D6",
    PokemonType.FIGHTING: "#C22E28",
    PokemonType.POISON: "#A33EA1",
    PokemonType.GROUND: "#E2BF65",
    PokemonType.FLYING: "#A98FF3",
    PokemonType.PSYCHIC: "#F95587",
    PokemonType.BUG: "#A6B91A",
    PokemonType.ROCK: "#B6A136",
    PokemonType.GHOST: "#735797",
    PokemonType.DRAGON: "#6F35FC",
    PokemonType.DARK: "#705746",
    PokemonType.STEEL: "#B7B7CE",
    PokemonType.FAIRY: "#D685AD",
}

# Type effectiveness chart (18x18).
# Keys: (attack_type, defender_type). Values: 1.6 (super effective), 1.0 (neutral),
# 0.625 (not very effective), 0.39 (immune/double resist — min posible en GO).
TYPE_EFFECTIVENESS: dict[tuple[str, str], float] = {
    ("normal", "rock"): 0.625,
    ("normal", "ghost"): 0.39,
    ("normal", "steel"): 0.625,
    ("fire", "fire"): 0.625,
    ("fire", "water"): 0.625,
    ("fire", "grass"): 1.6,
    ("fire", "ice"): 1.6,
    ("fire", "bug"): 1.6,
    ("fire", "rock"): 0.625,
    ("fire", "dragon"): 0.625,
    ("fire", "steel"): 1.6,
    ("water", "fire"): 1.6,
    ("water", "water"): 0.625,
    ("water", "grass"): 0.625,
    ("water", "ground"): 1.6,
    ("water", "rock"): 1.6,
    ("water", "dragon"): 0.625,
    ("electric", "water"): 1.6,
    ("electric", "electric"): 0.625,
    ("electric", "grass"): 0.625,
    ("electric", "ground"): 0.39,
    ("electric", "flying"): 1.6,
    ("electric", "dragon"): 0.625,
    ("grass", "fire"): 0.625,
    ("grass", "water"): 1.6,
    ("grass", "grass"): 0.625,
    ("grass", "poison"): 0.625,
    ("grass", "ground"): 1.6,
    ("grass", "flying"): 0.625,
    ("grass", "bug"): 0.625,
    ("grass", "rock"): 1.6,
    ("grass", "dragon"): 0.625,
    ("grass", "steel"): 0.625,
    ("ice", "fire"): 0.625,
    ("ice", "water"): 0.625,
    ("ice", "grass"): 1.6,
    ("ice", "ice"): 0.625,
    ("ice", "ground"): 1.6,
    ("ice", "flying"): 1.6,
    ("ice", "dragon"): 1.6,
    ("ice", "steel"): 0.625,
    ("fighting", "normal"): 1.6,
    ("fighting", "ice"): 1.6,
    ("fighting", "poison"): 0.625,
    ("fighting", "flying"): 0.625,
    ("fighting", "psychic"): 0.625,
    ("fighting", "bug"): 0.625,
    ("fighting", "rock"): 1.6,
    ("fighting", "ghost"): 0.39,
    ("fighting", "dark"): 1.6,
    ("fighting", "steel"): 1.6,
    ("fighting", "fairy"): 0.625,
    ("poison", "poison"): 0.625,
    ("poison", "ground"): 0.625,
    ("poison", "rock"): 0.625,
    ("poison", "ghost"): 0.625,
    ("poison", "steel"): 0.39,
    ("poison", "fairy"): 1.6,
    ("ground", "fire"): 1.6,
    ("ground", "grass"): 0.625,
    ("ground", "electric"): 1.6,
    ("ground", "poison"): 1.6,
    ("ground", "flying"): 0.39,
    ("ground", "bug"): 0.625,
    ("ground", "rock"): 1.6,
    ("ground", "steel"): 1.6,
    ("flying", "grass"): 1.6,
    ("flying", "electric"): 0.625,
    ("flying", "fighting"): 1.6,
    ("flying", "bug"): 1.6,
    ("flying", "rock"): 0.625,
    ("flying", "steel"): 0.625,
    ("psychic", "fighting"): 1.6,
    ("psychic", "poison"): 1.6,
    ("psychic", "psychic"): 0.625,
    ("psychic", "steel"): 0.625,
    ("psychic", "dark"): 0.39,
    ("bug", "fire"): 0.625,
    ("bug", "grass"): 1.6,
    ("bug", "fighting"): 0.625,
    ("bug", "poison"): 0.625,
    ("bug", "flying"): 0.625,
    ("bug", "psychic"): 1.6,
    ("bug", "ghost"): 0.625,
    ("bug", "dark"): 1.6,
    ("bug", "steel"): 0.625,
    ("bug", "fairy"): 0.625,
    ("rock", "fire"): 1.6,
    ("rock", "water"): 0.625,
    ("rock", "grass"): 0.625,
    ("rock", "fighting"): 0.625,
    ("rock", "ground"): 0.625,
    ("rock", "flying"): 1.6,
    ("rock", "bug"): 1.6,
    ("rock", "ice"): 1.6,
    ("rock", "steel"): 0.625,
    ("ghost", "normal"): 0.39,
    ("ghost", "psychic"): 1.6,
    ("ghost", "ghost"): 1.6,
    ("ghost", "dark"): 0.625,
    ("dragon", "dragon"): 1.6,
    ("dragon", "steel"): 0.625,
    ("dragon", "fairy"): 0.39,
    ("dark", "fighting"): 0.625,
    ("dark", "psychic"): 1.6,
    ("dark", "ghost"): 1.6,
    ("dark", "dark"): 0.625,
    ("dark", "fairy"): 0.625,
    ("steel", "fire"): 0.625,
    ("steel", "water"): 0.625,
    ("steel", "electric"): 0.625,
    ("steel", "ice"): 1.6,
    ("steel", "rock"): 1.6,
    ("steel", "steel"): 0.625,
    ("steel", "fairy"): 1.6,
    ("fairy", "fire"): 0.625,
    ("fairy", "fighting"): 1.6,
    ("fairy", "poison"): 0.625,
    ("fairy", "dragon"): 1.6,
    ("fairy", "dark"): 1.6,
    ("fairy", "steel"): 0.625,
}


@dataclass(frozen=True)
class BaseStats:
    atk: int
    def_: int
    sta: int


@dataclass(frozen=True)
class SpeciesInfo:
    dex: int
    name: str
    type1: str
    type2: str | None
    stats: BaseStats


@dataclass(frozen=True)
class FastMove:
    name: str
    type: str
    power: int
    duration_ticks: float
    energy_gain: int


@dataclass(frozen=True)
class ChargeMove:
    name: str
    type: str
    power: int
    duration_ticks: float
    energy_cost: int


# Fast moves (PvE)
# duration_ticks: 0.5s per tick in GO — we store ticks for precision
FAST_MOVES: dict[str, FastMove] = {
    "dragon_breath": FastMove("Dragon Breath", "dragon", 6, 1, 4),
    "dragon_tail": FastMove("Dragon Tail", "dragon", 15, 3, 3),
    "double_kick": FastMove("Double Kick", "fighting", 10, 2, 8),
    "shadow_claw": FastMove("Shadow Claw", "ghost", 9, 2, 4),
    "counter": FastMove("Counter", "fighting", 12, 2, 4),
    "karate_chop": FastMove("Karate Chop", "fighting", 8, 1, 4),
    "bullet_punch": FastMove("Bullet Punch", "steel", 9, 2, 4),
    "mud_shot": FastMove("Mud Shot", "ground", 5, 1, 5),
    "mud_slap": FastMove("Mud Slap", "ground", 11, 3, 3),
    "fire_spin": FastMove("Fire Spin", "fire", 14, 2, 3),
    "fire_fang": FastMove("Fire Fang", "fire", 12, 2, 2),
    "ember": FastMove("Ember", "fire", 10, 2, 4),
    "incinerate": FastMove("Incinerate", "fire", 29, 5, 4),
    "water_gun": FastMove("Water Gun", "water", 5, 1, 5),
    "waterfall": FastMove("Waterfall", "water", 16, 3, 3),
    "vine_whip": FastMove("Vine Whip", "grass", 7, 2, 4),
    "razor_leaf": FastMove("Razor Leaf", "grass", 13, 3, 2),
    "bullet_seed": FastMove("Bullet Seed", "grass", 8, 2, 4),
    "thunder_shock": FastMove("Thunder Shock", "electric", 5, 1, 5),
    "charge_beam": FastMove("Charge Beam", "electric", 5, 1, 5),
    "spark": FastMove("Spark", "electric", 7, 2, 4),
    "ice_shard": FastMove("Ice Shard", "ice", 12, 3, 3),
    "powder_snow": FastMove("Powder Snow", "ice", 6, 1, 4),
    "frost_breath": FastMove("Frost Breath", "ice", 10, 2, 3),
    "lick": FastMove("Lick", "ghost", 5, 1, 4),
    "psycho_cut": FastMove("Psycho Cut", "psychic", 5, 1, 5),
    "confusion": FastMove("Confusion", "psychic", 16, 3, 3),
    "zen_headbutt": FastMove("Zen Headbutt", "psychic", 12, 3, 2),
    "snarl": FastMove("Snarl", "dark", 10, 2, 4),
    "bite": FastMove("Bite", "dark", 6, 1, 2),
    "feint_attack": FastMove("Feint Attack", "dark", 10, 2, 3),
    "sucker_punch": FastMove("Sucker Punch", "dark", 7, 2, 3),
    "wing_attack": FastMove("Wing Attack", "flying", 8, 2, 4),
    "air_slash": FastMove("Air Slash", "flying", 12, 2, 3),
    "peck": FastMove("Peck", "flying", 10, 2, 3),
    "poison_jab": FastMove("Poison Jab", "poison", 10, 2, 4),
    "poison_sting": FastMove("Poison Sting", "poison", 5, 1, 4),
    "extrasensory": FastMove("Extrasensory", "psychic", 12, 3, 4),
    "rock_throw": FastMove("Rock Throw", "rock", 12, 2, 3),
    "smack_down": FastMove("Smack Down", "rock", 16, 3, 3),
    "rock_blast_ft": FastMove("Rock Blast", "rock", 7, 2, 3),
    "bug_bite": FastMove("Bug Bite", "bug", 5, 1, 4),
    "fury_cutter": FastMove("Fury Cutter", "bug", 4, 1, 4),
    "infestation": FastMove("Infestation", "bug", 10, 2, 4),
    "metal_claw": FastMove("Metal Claw", "steel", 8, 2, 4),
    "steel_wing": FastMove("Steel Wing", "steel", 11, 2, 3),
    "quick_attack": FastMove("Quick Attack", "normal", 8, 1, 3),
    "pound": FastMove("Pound", "normal", 7, 1, 3),
    "tackle": FastMove("Tackle", "normal", 5, 1, 3),
    "scratch": FastMove("Scratch", "normal", 6, 1, 4),
    "present": FastMove("Present", "normal", 7, 2, 4),
    "astonish": FastMove("Astonish", "ghost", 8, 2, 4),
    "hex": FastMove("Hex", "ghost", 10, 2, 4),
    "cut": FastMove("Cut", "normal", 5, 1, 3),
    "low_kick": FastMove("Low Kick", "fighting", 5, 1, 3),
    "rock_smash": FastMove("Rock Smash", "fighting", 9, 2, 2),
    "water_shuriken": FastMove("Water Shuriken", "water", 5, 1, 5),
    "gust": FastMove("Gust", "flying", 10, 2, 3),
    "thunder_fang": FastMove("Thunder Fang", "electric", 12, 2, 2),
    "ice_fang": FastMove("Ice Fang", "ice", 8, 2, 2),
    "fire_fang2": FastMove("Fire Fang", "fire", 12, 2, 2),
    "shadow_sneak_ft": FastMove("Shadow Sneak", "ghost", 10, 2, 4),
    "yawn": FastMove("Yawn", "normal", 0, 2, 4),
    "splash": FastMove("Splash", "normal", 0, 2, 4),
    "transform": FastMove("Transform", "normal", 0, 2, 0),
    "hidden_power": FastMove("Hidden Power", "normal", 9, 2, 4),
    "struggle_ft": FastMove("Struggle", "normal", 6, 2, 0),
}

# Charge moves (PvE)
CHARGE_MOVES: dict[str, ChargeMove] = {
    "dragon_claw": ChargeMove("Dragon Claw", "dragon", 50, 3, 35),
    "outrage": ChargeMove("Outrage", "dragon", 110, 5, 50),
    "draco_meteor": ChargeMove("Draco Meteor", "dragon", 150, 5, 65),
    "dragon_pulse": ChargeMove("Dragon Pulse", "dragon", 90, 4, 50),
    "shadow_ball": ChargeMove("Shadow Ball", "ghost", 100, 3, 50),
    "shadow_force": ChargeMove("Shadow Force", "ghost", 140, 3, 60),
    "focus_blast": ChargeMove("Focus Blast", "fighting", 150, 5, 65),
    "close_combat": ChargeMove("Close Combat", "fighting", 100, 5, 45),
    "dynamic_punch": ChargeMove("Dynamic Punch", "fighting", 90, 4, 50),
    "superpower": ChargeMove("Superpower", "fighting", 85, 3, 40),
    "aura_sphere": ChargeMove("Aura Sphere", "fighting", 100, 3, 50),
    "meteor_mash": ChargeMove("Meteor Mash", "steel", 100, 4, 50),
    "iron_head": ChargeMove("Iron Head", "steel", 70, 3, 50),
    "flash_cannon": ChargeMove("Flash Cannon", "steel", 110, 4, 60),
    "heavy_slam": ChargeMove("Heavy Slam", "steel", 70, 3, 50),
    "hurricane": ChargeMove("Hurricane", "flying", 110, 5, 55),
    "earthquake": ChargeMove("Earthquake", "ground", 120, 4, 60),
    "earth_power": ChargeMove("Earth Power", "ground", 100, 4, 50),
    "drill_run": ChargeMove("Drill Run", "ground", 80, 3, 45),
    "scorching_sands": ChargeMove("Scorching Sands", "ground", 80, 3, 50),
    "fire_blast": ChargeMove("Fire Blast", "fire", 140, 5, 65),
    "overheat": ChargeMove("Overheat", "fire", 130, 5, 55),
    "flamethrower": ChargeMove("Flamethrower", "fire", 70, 3, 50),
    "fire_punch": ChargeMove("Fire Punch", "fire", 55, 3, 40),
    "blast_burn": ChargeMove("Blast Burn", "fire", 110, 4, 50),
    "hydro_pump": ChargeMove("Hydro Pump", "water", 130, 4, 60),
    "surf": ChargeMove("Surf", "water", 65, 3, 45),
    "water_pulse": ChargeMove("Water Pulse", "water", 70, 3, 50),
    "aqua_tail": ChargeMove("Aqua Tail", "water", 50, 3, 35),
    "hydro_cannon": ChargeMove("Hydro Cannon", "water", 90, 3, 45),
    "solar_beam": ChargeMove("Solar Beam", "grass", 150, 5, 65),
    "grass_knot": ChargeMove("Grass Knot", "grass", 90, 3, 50),
    "frenzy_plant": ChargeMove("Frenzy Plant", "grass", 110, 4, 50),
    "leaf_blade": ChargeMove("Leaf Blade", "grass", 70, 3, 35),
    "seed_bomb": ChargeMove("Seed Bomb", "grass", 55, 3, 40),
    "wild_charge": ChargeMove("Wild Charge", "electric", 100, 3, 45),
    "thunderbolt": ChargeMove("Thunderbolt", "electric", 80, 3, 50),
    "thunder": ChargeMove("Thunder", "electric", 100, 4, 60),
    "zap_cannon": ChargeMove("Zap Cannon", "electric", 150, 5, 65),
    "discharge": ChargeMove("Discharge", "electric", 65, 3, 45),
    "ice_beam": ChargeMove("Ice Beam", "ice", 90, 4, 50),
    "blizzard": ChargeMove("Blizzard", "ice", 130, 5, 65),
    "avalanche": ChargeMove("Avalanche", "ice", 90, 3, 50),
    "ice_punch": ChargeMove("Ice Punch", "ice", 55, 3, 40),
    "weather_ball_ice": ChargeMove("Weather Ball (Ice)", "ice", 55, 3, 35),
    "psychic_move": ChargeMove("Psychic", "psychic", 90, 3, 50),
    "psystrike": ChargeMove("Psystrike", "psychic", 100, 3, 45),
    "psychic_fangs": ChargeMove("Psychic Fangs", "psychic", 40, 2, 30),
    "future_sight": ChargeMove("Future Sight", "psychic", 120, 3, 55),
    "dark_pulse": ChargeMove("Dark Pulse", "dark", 80, 3, 50),
    "foul_play": ChargeMove("Foul Play", "dark", 70, 3, 45),
    "brutal_swing": ChargeMove("Brutal Swing", "dark", 65, 2, 40),
    "crunch": ChargeMove("Crunch", "dark", 70, 3, 45),
    "brave_bird": ChargeMove("Brave Bird", "flying", 130, 3, 55),
    "sky_attack": ChargeMove("Sky Attack", "flying", 80, 3, 45),
    "aerial_ace": ChargeMove("Aerial Ace", "flying", 55, 3, 40),
    "drill_peck": ChargeMove("Drill Peck", "flying", 65, 3, 40),
    "flying_press": ChargeMove("Flying Press", "flying", 110, 4, 55),
    "sludge_bomb": ChargeMove("Sludge Bomb", "poison", 80, 3, 50),
    "sludge_wave": ChargeMove("Sludge Wave", "poison", 110, 4, 55),
    "gunk_shot": ChargeMove("Gunk Shot", "poison", 130, 4, 60),
    "stone_edge": ChargeMove("Stone Edge", "rock", 100, 3, 55),
    "rock_slide": ChargeMove("Rock Slide", "rock", 80, 3, 50),
    "rock_tomb": ChargeMove("Rock Tomb", "rock", 70, 4, 40),
    "power_gem": ChargeMove("Power Gem", "rock", 80, 3, 50),
    "meteor_beam": ChargeMove("Meteor Beam", "rock", 140, 4, 60),
    "x_scissor": ChargeMove("X-Scissor", "bug", 45, 3, 35),
    "bug_buzz": ChargeMove("Bug Buzz", "bug", 100, 4, 60),
    "megahorn": ChargeMove("Megahorn", "bug", 110, 4, 55),
    "signal_beam": ChargeMove("Signal Beam", "bug", 75, 3, 45),
    "play_rough": ChargeMove("Play Rough", "fairy", 90, 3, 50),
    "dazzling_gleam": ChargeMove("Dazzling Gleam", "fairy", 110, 4, 60),
    "moonblast": ChargeMove("Moonblast", "fairy", 110, 4, 50),
    "disarming_voice": ChargeMove("Disarming Voice", "fairy", 70, 3, 45),
    "hyper_beam": ChargeMove("Hyper Beam", "normal", 150, 5, 65),
    "hyper_voice": ChargeMove("Hyper Voice", "normal", 90, 4, 50),
    "body_slam": ChargeMove("Body Slam", "normal", 50, 2, 35),
    "last_resort": ChargeMove("Last Resort", "normal", 90, 3, 50),
    "giga_impact": ChargeMove("Giga Impact", "normal", 120, 5, 60),
    "return": ChargeMove("Return", "normal", 130, 4, 60),
    "frustration": ChargeMove("Frustration", "normal", 10, 1, 5),
    "night_slash": ChargeMove("Night Slash", "dark", 50, 3, 35),
    "payback": ChargeMove("Payback", "dark", 100, 3, 60),
    "shadow_claw_cg": ChargeMove("Shadow Claw", "ghost", 50, 3, 35),
    "shadow_punch": ChargeMove("Shadow Punch", "ghost", 40, 2, 35),
    "ominous_wind": ChargeMove("Ominous Wind", "ghost", 50, 3, 45),
    "lunge": ChargeMove("Lunge", "bug", 60, 3, 40),
    "acid_spray": ChargeMove("Acid Spray", "poison", 20, 3, 40),
    "weather_ball_fire": ChargeMove("Weather Ball (Fire)", "fire", 55, 3, 35),
    "weather_ball_water": ChargeMove("Weather Ball (Water)", "water", 55, 3, 35),
    "weather_ball_rock": ChargeMove("Weather Ball (Rock)", "rock", 55, 3, 35),
    "tri_attack": ChargeMove("Tri Attack", "normal", 75, 3, 50),
    "doom_desire": ChargeMove("Doom Desire", "steel", 85, 3, 40),
    "double_iron_bash": ChargeMove("Double Iron Bash", "steel", 100, 4, 50),
    "mirror_shot": ChargeMove("Mirror Shot", "steel", 50, 3, 40),
    "gyro_ball": ChargeMove("Gyro Ball", "steel", 80, 3, 50),
    "liquidation": ChargeMove("Liquidation", "water", 70, 3, 45),
    "scald": ChargeMove("Scald", "water", 80, 3, 50),
    "octazooka": ChargeMove("Octazooka", "water", 50, 3, 40),
    "bone_club": ChargeMove("Bone Club", "ground", 55, 3, 40),
    "dig": ChargeMove("Dig", "ground", 100, 4, 50),
    "bulldoze": ChargeMove("Bulldoze", "ground", 80, 3, 50),
    "mud_bomb": ChargeMove("Mud Bomb", "ground", 55, 2, 40),
    "energy_ball": ChargeMove("Energy Ball", "grass", 90, 3, 55),
    "petal_blizzard": ChargeMove("Petal Blizzard", "grass", 110, 4, 50),
    "solar_blade": ChargeMove("Solar Blade", "grass", 140, 3, 55),
    "power_whip": ChargeMove("Power Whip", "grass", 90, 3, 50),
    "ice_beam2": ChargeMove("Ice Beam", "ice", 90, 4, 50),
    "icy_wind": ChargeMove("Icy Wind", "ice", 60, 3, 45),
    "triple_axel": ChargeMove("Triple Axel", "ice", 60, 3, 40),
    "psychic_boost": ChargeMove("Psyshock", "psychic", 65, 3, 40),
    "stored_power": ChargeMove("Stored Power", "psychic", 60, 3, 45),
    "iron_head_cg": ChargeMove("Iron Head", "steel", 70, 3, 50),
    "mirror_coat": ChargeMove("Mirror Coat", "psychic", 60, 3, 45),
    "ancient_power": ChargeMove("Ancient Power", "rock", 70, 3, 45),
    "rock_wrecker": ChargeMove("Rock Wrecker", "rock", 110, 4, 50),
    "head_smash": ChargeMove("Head Smash", "rock", 110, 3, 55),
    "fell_stinger": ChargeMove("Fell Stinger", "bug", 20, 2, 35),
    "silver_wind": ChargeMove("Silver Wind", "bug", 50, 3, 45),
    "horn_attack": ChargeMove("Horn Attack", "normal", 40, 3, 35),
    "stomp": ChargeMove("Stomp", "normal", 55, 3, 40),
    "swift": ChargeMove("Swift", "normal", 55, 2, 35),
    "thunder_punch": ChargeMove("Thunder Punch", "electric", 55, 3, 40),
    "thunder_shock_cg": ChargeMove("Thunder Shock", "electric", 55, 3, 40),
    "ice_punch_cg": ChargeMove("Ice Punch", "ice", 55, 3, 40),
    "fire_punch_cg": ChargeMove("Fire Punch", "fire", 55, 3, 40),
    "drain_punch": ChargeMove("Drain Punch", "fighting", 50, 3, 40),
    "brick_break": ChargeMove("Brick Break", "fighting", 40, 3, 35),
    "rock_smash_cg": ChargeMove("Rock Smash", "fighting", 50, 3, 40),
    "cross_chop": ChargeMove("Cross Chop", "fighting", 55, 2, 40),
    "sacred_sword": ChargeMove("Sacred Sword", "fighting", 55, 2, 35),
    "mach_punch": ChargeMove("Mach Punch", "fighting", 40, 2, 30),
    "power_up_punch": ChargeMove("Power-Up Punch", "fighting", 20, 2, 30),
    "seed_flare": ChargeMove("Seed Flare", "grass", 130, 4, 55),
    "leaf_storm": ChargeMove("Leaf Storm", "grass", 130, 4, 55),
    "muddy_water": ChargeMove("Muddy Water", "water", 50, 3, 40),
    "origin_pulse": ChargeMove("Origin Pulse", "water", 130, 3, 55),
    "precipice_blades": ChargeMove("Precipice Blades", "ground", 130, 3, 55),
    "aeroblast": ChargeMove("Aeroblast", "flying", 120, 4, 55),
    "sacred_fire": ChargeMove("Sacred Fire", "fire", 120, 4, 55),
    "luster_purge": ChargeMove("Luster Purge", "psychic", 120, 4, 55),
    "mist_ball": ChargeMove("Mist Ball", "psychic", 120, 4, 55),
    "fusion_flare": ChargeMove("Fusion Flare", "fire", 140, 4, 60),
    "fusion_bolt": ChargeMove("Fusion Bolt", "electric", 140, 4, 60),
    "glaciate": ChargeMove("Glaciate", "ice", 120, 4, 50),
    "freeze_shock": ChargeMove("Freeze Shock", "ice", 140, 4, 55),
    "ice_burn": ChargeMove("Ice Burn", "ice", 140, 4, 55),
    "techno_blast_normal": ChargeMove("Techno Blast (Normal)", "normal", 120, 3, 50),
    "techno_blast_fire": ChargeMove("Techno Blast (Fire)", "fire", 120, 3, 50),
    "techno_blast_water": ChargeMove("Techno Blast (Water)", "water", 120, 3, 50),
    "techno_blast_electric": ChargeMove("Techno Blast (Electric)", "electric", 120, 3, 50),
    "techno_blast_ice": ChargeMove("Techno Blast (Ice)", "ice", 120, 3, 50),
    "searing_shot": ChargeMove("Searing Shot", "fire", 120, 4, 55),
    "v_create": ChargeMove("V Create", "fire", 120, 3, 50),
    "bolt_strike": ChargeMove("Bolt Strike", "electric", 130, 3, 55),
    "blue_flare": ChargeMove("Blue Flare", "fire", 130, 3, 55),
    "fiery_dance": ChargeMove("Fiery Dance", "fire", 80, 3, 50),
    "spacial_rend": ChargeMove("Spacial Rend", "dragon", 110, 3, 50),
    "roar_of_time": ChargeMove("Roar of Time", "dragon", 150, 4, 60),
    "magma_storm": ChargeMove("Magma Storm", "fire", 130, 4, 55),
    "oblivion_wing": ChargeMove("Oblivion Wing", "flying", 100, 3, 50),
    "diamond_storm": ChargeMove("Diamond Storm", "rock", 100, 3, 50),
    "moonlight": ChargeMove("Moonlight", "fairy", 100, 4, 55),
    "sunsteel_strike": ChargeMove("Sunsteel Strike", "steel", 130, 3, 50),
    "moongeist_beam": ChargeMove("Moongeist Beam", "ghost", 130, 3, 50),
    "photonic_geyser": ChargeMove("Photonic Geyser", "psychic", 130, 3, 55),
    "behemoth_blade": ChargeMove("Behemoth Blade", "steel", 120, 4, 50),
    "behemoth_bash": ChargeMove("Behemoth Bash", "steel", 120, 4, 50),
    "astral_barrage": ChargeMove("Astral Barrage", "ghost", 130, 3, 55),
    "glacial_lance": ChargeMove("Glacial Lance", "ice", 130, 3, 50),
    "adamant_axe": ChargeMove("Adamant Axe", "dragon", 90, 3, 40),
}

# Best movesets per species: (fast_move_key, charge_move_key)
BEST_MOVESETS: dict[str, tuple[str, str]] = {
    "rayquaza": ("dragon_tail", "outrage"),
    "garchomp": ("dragon_tail", "outrage"),
    "salamence": ("dragon_tail", "draco_meteor"),
    "dragonite": ("dragon_tail", "outrage"),
    "palkia": ("dragon_tail", "draco_meteor"),
    "dialga": ("dragon_breath", "draco_meteor"),
    "zekrom": ("dragon_breath", "outrage"),
    "reshiram": ("dragon_breath", "draco_meteor"),
    "latios": ("dragon_breath", "dragon_claw"),
    "kyurem": ("dragon_breath", "draco_meteor"),
    "giratina_origin": ("shadow_claw", "shadow_ball"),
    "giratina_altered": ("shadow_claw", "shadow_ball"),
    "darkrai": ("snarl", "dark_pulse"),
    "tyranitar": ("bite", "crunch"),
    "hydreigon": ("bite", "dark_pulse"),
    "weavile": ("snarl", "foul_play"),
    "honchkrow": ("snarl", "dark_pulse"),
    "zarude": ("vine_whip", "power_whip"),
    "kartana": ("razor_leaf", "leaf_blade"),
    "tapu_bulu": ("bullet_seed", "grass_knot"),
    "roserade": ("poison_jab", "grass_knot"),
    "sceptile": ("bullet_seed", "frenzy_plant"),
    "venusaur": ("vine_whip", "frenzy_plant"),
    "machamp": ("counter", "dynamic_punch"),
    "conkeldurr": ("counter", "dynamic_punch"),
    "lucario": ("counter", "aura_sphere"),
    "breloom": ("counter", "focus_blast"),
    "keldeo": ("counter", "sacred_sword"),
    "terrakion": ("double_kick", "sacred_sword"),
    "chandelure": ("fire_spin", "overheat"),
    "moltres": ("fire_spin", "overheat"),
    "entei": ("fire_fang", "flamethrower"),
    "blaziken": ("counter", "blast_burn"),
    "charizard": ("fire_spin", "blast_burn"),
    "darmanitan": ("fire_fang", "overheat"),
    "volcarona": ("fire_spin", "overheat"),
    "kyogre": ("waterfall", "surf"),
    "groudon": ("mud_shot", "earthquake"),
    "mamoswine": ("powder_snow", "avalanche"),
    "glaceon": ("frost_breath", "avalanche"),
    "weavile_ice": ("ice_shard", "avalanche"),
    "mewtwo": ("psycho_cut", "psystrike"),
    "espeon": ("confusion", "future_sight"),
    "metagross": ("bullet_punch", "meteor_mash"),
    "dusknoir": ("hex", "shadow_ball"),
    "rampardos": ("smack_down", "rock_slide"),
    "rhyperior": ("mud_slap", "rock_wrecker"),
    "raikou": ("thunder_shock", "wild_charge"),
    "magnezone": ("spark", "wild_charge"),
    "xurkitree": ("spark", "discharge"),
    "electivire": ("thunder_shock", "wild_charge"),
    "luxray": ("spark", "wild_charge"),
    "gengar": ("shadow_claw", "shadow_ball"),
    "blissey": ("pound", "hyper_beam"),
    "slaking": ("scratch", "body_slam"),
    "snorlax": ("lick", "body_slam"),
    "gyarados": ("waterfall", "aqua_tail"),
    "swampert": ("mud_shot", "hydro_cannon"),
    "feraligatr": ("waterfall", "hydro_cannon"),
    "empoleon": ("waterfall", "hydro_cannon"),
    "samurott": ("waterfall", "hydro_cannon"),
    "honchkrow_flying": ("peck", "sky_attack"),
    "moltres_flying": ("wing_attack", "sky_attack"),
    "staraptor": ("wing_attack", "brave_bird"),
    "unfezant": ("peck", "sky_attack"),
    "braviary": ("air_slash", "brave_bird"),
    "yanmega": ("wing_attack", "bug_buzz"),
    "scizor": ("bullet_punch", "x_scissor"),
    "heracross": ("counter", "megahorn"),
    "vikavolt": ("spark", "bug_buzz"),
    "genesect": ("fury_cutter", "x_scissor"),
    "toxicroak": ("counter", "sludge_bomb"),
    "nidoking": ("poison_jab", "earth_power"),
    "landorus_therian": ("mud_shot", "earth_power"),
    "excadrill": ("mud_shot", "drill_run"),
    "heatran": ("fire_spin", "flamethrower"),
    "cobalion": ("double_kick", "sacred_sword"),
    "virizion": ("double_kick", "leaf_blade"),
    "tornadus_therian": ("gust", "hurricane"),
    "thundurus_therian": ("thunder_shock", "thunderbolt"),
    "landorus_incarnate": ("mud_shot", "earth_power"),
    "pheromosa": ("bug_bite", "bug_buzz"),
    "buzzwole": ("counter", "superpower"),
    "xurkitree_2": ("spark", "discharge"),
    "celesteela": ("air_slash", "heavy_slam"),
    "nihilego": ("poison_jab", "gunk_shot"),
    "guzzlord": ("bite", "crunch"),
    "stakataka": ("smack_down", "stone_edge"),
    "blacephalon": ("incinerate", "fire_blast"),
    "naganadel": ("poison_jab", "dragon_pulse"),
    "melmetal": ("thunder_shock", "double_iron_bash"),
    "genesect_burn": ("fury_cutter", "flamethrower"),
    "genesect_chill": ("fury_cutter", "ice_beam"),
    "genesect_douse": ("fury_cutter", "surf"),
    "genesect_shock": ("fury_cutter", "zap_cannon"),
    "deoxys_attack": ("zen_headbutt", "psychic_boost"),
    "ho_oh": ("incinerate", "sacred_fire"),
    "lugia": ("extrasensory", "future_sight"),
    "regigigas": ("hidden_power", "giga_impact"),
    "latias": ("dragon_breath", "thunder"),
    "cresselia": ("psycho_cut", "moonblast"),
    "heatran_2": ("fire_spin", "flamethrower"),
    "regirock": ("rock_throw", "stone_edge"),
    "regice": ("frost_breath", "blizzard"),
    "registeel": ("metal_claw", "flash_cannon"),
    "azelf": ("confusion", "future_sight"),
    "mesprit": ("confusion", "future_sight"),
    "uxie": ("confusion", "future_sight"),
    "heatran_magma": ("fire_spin", "magma_storm"),
    "giratina_origin_shadow": ("shadow_claw", "shadow_ball"),
    "arceus_normal": ("hidden_power", "hyper_beam"),
    "arceus_water": ("waterfall", "surf"),
    "arceus_fire": ("fire_spin", "overheat"),
    "arceus_grass": ("vine_whip", "solar_beam"),
    "arceus_electric": ("charge_beam", "thunder"),
    "arceus_ice": ("frost_breath", "blizzard"),
    "arceus_fighting": ("counter", "focus_blast"),
    "arceus_ground": ("mud_shot", "earthquake"),
    "arceus_flying": ("air_slash", "sky_attack"),
    "arceus_psychic": ("confusion", "future_sight"),
    "arceus_bug": ("bug_bite", "bug_buzz"),
    "arceus_rock": ("smack_down", "stone_edge"),
    "arceus_ghost": ("shadow_claw", "shadow_ball"),
    "arceus_dragon": ("dragon_breath", "outrage"),
    "arceus_dark": ("snarl", "dark_pulse"),
    "arceus_steel": ("metal_claw", "flash_cannon"),
    "arceus_fairy": ("hidden_power", "moonblast"),
    "eternatus": ("poison_jab", "sludge_bomb"),
    "enamorus": ("confusion", "moonblast"),
    "urshifu_single": ("counter", "focus_blast"),
    "urshifu_rapid": ("counter", "aerial_ace"),
    "spectrier": ("lick", "shadow_ball"),
    "glastrier": ("ice_shard", "avalanche"),
    "calyrex_shadow": ("confusion", "shadow_ball"),
    "calyrex_ice": ("powder_snow", "avalanche"),
    "zacian": ("quick_attack", "play_rough"),
    "zamazenta": ("quick_attack", "moonblast"),
    "kubfu": ("counter", "focus_blast"),
    "wo_chien": ("vine_whip", "grass_knot"),
    "chien_pao": ("powder_snow", "avalanche"),
    "ting_lu": ("mud_shot", "earthquake"),
    "chi_yu": ("fire_spin", "overheat"),
    "ogerpon": ("vine_whip", "solar_beam"),
    "terapagos": ("confusion", "hyper_beam"),
    "pecharunt": ("astonish", "shadow_ball"),
    "okidogi": ("counter", "dynamic_punch"),
    "munkidori": ("confusion", "psychic_move"),
    "fezandipiti": ("peck", "moonblast"),
    "raging_bolt": ("dragon_breath", "thunder"),
    "gouging_fire": ("dragon_breath", "flamethrower"),
    "walking_wake": ("water_gun", "hydro_pump"),
    "iron_leaves": ("razor_leaf", "leaf_blade"),
    "iron_bundle": ("present", "ice_beam"),
    "iron_hands": ("counter", "close_combat"),
    "iron_treads": ("mud_shot", "earthquake"),
    "iron_moth": ("fire_spin", "overheat"),
    "iron_valiant": ("counter", "close_combat"),
    "iron_crown": ("psycho_cut", "psychic_move"),
    "iron_jugulis": ("bite", "dark_pulse"),
    "iron_thorns": ("bite", "stone_edge"),
    "roaring_moon": ("dragon_tail", "outrage"),
    "flutter_mane": ("astonish", "shadow_ball"),
    "scream_tail": ("tackle", "play_rough"),
    "brute_bonnet": ("vine_whip", "seed_bomb"),
    "sandshrew_alola": ("powder_snow", "ice_punch"),
    "sandslash_alola": ("powder_snow", "ice_punch"),
    "ninetales_alola": ("powder_snow", "blizzard"),
    "wigglytuff": ("feint_attack", "play_rough"),
    "parasect": ("bug_bite", "x_scissor"),
    "venomoth": ("infestation", "bug_buzz"),
    "primeape": ("counter", "cross_chop"),
    "arcanine": ("fire_fang", "flamethrower"),
    "victreebel": ("razor_leaf", "leaf_blade"),
    "tentacruel": ("poison_jab", "sludge_wave"),
    "golem": ("rock_throw", "stone_edge"),
    "cloyster": ("frost_breath", "avalanche"),
    "hypno": ("confusion", "psychic_move"),
    "kingler": ("waterfall", "liquidation"),
    "electrode": ("spark", "thunderbolt"),
    "exeggutor": ("confusion", "solar_beam"),
    "marowak_alola": ("fire_spin", "shadow_ball"),
    "hitmonlee": ("low_kick", "close_combat"),
    "hitmonchan": ("bullet_punch", "close_combat"),
    "lickitung": ("lick", "body_slam"),
    "rhydon": ("mud_slap", "earthquake"),
    "tangela": ("vine_whip", "power_whip"),
    "kangaskhan": ("mud_shot", "return"),
    "pinsir": ("bug_bite", "x_scissor"),
    "omastar": ("waterfall", "surf"),
    "kabutops": ("waterfall", "liquidation"),
    "aerodactyl": ("rock_throw", "rock_slide"),
    "jolteon": ("thunder_shock", "wild_charge"),
    "flareon": ("fire_spin", "overheat"),
    "vaporeon": ("water_gun", "aqua_tail"),
    "leafeon": ("razor_leaf", "leaf_blade"),
    "umbreon": ("snarl", "foul_play"),
    "jynx": ("frost_breath", "avalanche"),
    "magmar": ("ember", "fire_blast"),
    "eelektross": ("spark", "wild_charge"),
}

SPECIES: dict[str, SpeciesInfo] = {
    "venusaur": SpeciesInfo(3, "Venusaur", "grass", "poison", BaseStats(198, 189, 190)),
    "charizard": SpeciesInfo(6, "Charizard", "fire", "flying", BaseStats(223, 173, 186)),
    "blastoise": SpeciesInfo(9, "Blastoise", "water", None, BaseStats(171, 207, 188)),
    "raichu": SpeciesInfo(26, "Raichu", "electric", None, BaseStats(193, 151, 155)),
    "sandshrew_alola": SpeciesInfo(
        27, "Sandshrew (Alola)", "ice", "steel", BaseStats(126, 145, 137)
    ),
    "sandslash_alola": SpeciesInfo(
        28, "Sandslash (Alola)", "ice", "steel", BaseStats(177, 180, 181)
    ),
    "ninetales_alola": SpeciesInfo(
        38, "Ninetales (Alola)", "ice", "fairy", BaseStats(170, 199, 177)
    ),
    "wigglytuff": SpeciesInfo(40, "Wigglytuff", "normal", "fairy", BaseStats(156, 93, 295)),
    "parasect": SpeciesInfo(47, "Parasect", "bug", "grass", BaseStats(165, 146, 155)),
    "venomoth": SpeciesInfo(49, "Venomoth", "bug", "poison", BaseStats(179, 150, 172)),
    "primeape": SpeciesInfo(57, "Primeape", "fighting", None, BaseStats(207, 138, 163)),
    "arcanine": SpeciesInfo(59, "Arcanine", "fire", None, BaseStats(227, 166, 207)),
    "victreebel": SpeciesInfo(71, "Victreebel", "grass", "poison", BaseStats(207, 135, 190)),
    "tentacruel": SpeciesInfo(73, "Tentacruel", "water", "poison", BaseStats(166, 209, 190)),
    "golem": SpeciesInfo(76, "Golem", "rock", "ground", BaseStats(211, 198, 190)),
    "cloyster": SpeciesInfo(91, "Cloyster", "water", "ice", BaseStats(186, 323, 137)),
    "gengar": SpeciesInfo(94, "Gengar", "ghost", "poison", BaseStats(261, 149, 155)),
    "hypno": SpeciesInfo(97, "Hypno", "psychic", None, BaseStats(144, 193, 198)),
    "kingler": SpeciesInfo(99, "Kingler", "water", None, BaseStats(178, 115, 146)),
    "electrode": SpeciesInfo(101, "Electrode", "electric", None, BaseStats(173, 173, 155)),
    "exeggutor": SpeciesInfo(103, "Exeggutor", "grass", "psychic", BaseStats(233, 149, 216)),
    "marowak_alola": SpeciesInfo(105, "Marowak (Alola)", "fire", "ghost", BaseStats(144, 186, 155)),
    "hitmonlee": SpeciesInfo(106, "Hitmonlee", "fighting", None, BaseStats(224, 181, 137)),
    "hitmonchan": SpeciesInfo(107, "Hitmonchan", "fighting", None, BaseStats(193, 197, 137)),
    "lickitung": SpeciesInfo(108, "Lickitung", "normal", None, BaseStats(108, 137, 233)),
    "rhyhorn": SpeciesInfo(111, "Rhyhorn", "ground", "rock", BaseStats(140, 127, 190)),
    "rhydon": SpeciesInfo(112, "Rhydon", "ground", "rock", BaseStats(222, 170, 233)),
    "tangela": SpeciesInfo(114, "Tangela", "grass", None, BaseStats(183, 169, 163)),
    "kangaskhan": SpeciesInfo(115, "Kangaskhan", "normal", None, BaseStats(181, 165, 233)),
    "pinsir": SpeciesInfo(127, "Pinsir", "bug", None, BaseStats(238, 182, 163)),
    "gyarados": SpeciesInfo(130, "Gyarados", "water", "flying", BaseStats(237, 186, 216)),
    "lapras": SpeciesInfo(131, "Lapras", "water", "ice", BaseStats(165, 174, 277)),
    "ditto": SpeciesInfo(132, "Ditto", "normal", None, BaseStats(91, 91, 134)),
    "vaporeon": SpeciesInfo(134, "Vaporeon", "water", None, BaseStats(205, 161, 277)),
    "jolteon": SpeciesInfo(135, "Jolteon", "electric", None, BaseStats(232, 182, 163)),
    "flareon": SpeciesInfo(136, "Flareon", "fire", None, BaseStats(246, 179, 163)),
    "omastar": SpeciesInfo(139, "Omastar", "rock", "water", BaseStats(207, 201, 172)),
    "kabutops": SpeciesInfo(141, "Kabutops", "rock", "water", BaseStats(220, 186, 155)),
    "aerodactyl": SpeciesInfo(142, "Aerodactyl", "rock", "flying", BaseStats(221, 159, 190)),
    "snorlax": SpeciesInfo(143, "Snorlax", "normal", None, BaseStats(190, 169, 330)),
    "dragonite": SpeciesInfo(149, "Dragonite", "dragon", "flying", BaseStats(263, 198, 209)),
    "mewtwo": SpeciesInfo(150, "Mewtwo", "psychic", None, BaseStats(300, 182, 214)),
    "mew": SpeciesInfo(151, "Mew", "psychic", None, BaseStats(210, 210, 225)),
    "ampharos": SpeciesInfo(181, "Ampharos", "electric", None, BaseStats(211, 169, 207)),
    "umbreon": SpeciesInfo(197, "Umbreon", "dark", None, BaseStats(126, 240, 216)),
    "kingdra": SpeciesInfo(230, "Kingdra", "water", "dragon", BaseStats(194, 194, 181)),
    "blissey": SpeciesInfo(242, "Blissey", "normal", None, BaseStats(129, 169, 496)),
    "raikou": SpeciesInfo(243, "Raikou", "electric", None, BaseStats(241, 195, 207)),
    "entei": SpeciesInfo(244, "Entei", "fire", None, BaseStats(235, 171, 251)),
    "suicune": SpeciesInfo(245, "Suicune", "water", None, BaseStats(180, 235, 225)),
    "tyranitar": SpeciesInfo(248, "Tyranitar", "rock", "dark", BaseStats(251, 207, 225)),
    "lugia": SpeciesInfo(249, "Lugia", "psychic", "flying", BaseStats(193, 323, 235)),
    "ho_oh": SpeciesInfo(250, "Ho-Oh", "fire", "flying", BaseStats(239, 244, 239)),
    "sceptile": SpeciesInfo(254, "Sceptile", "grass", None, BaseStats(223, 169, 172)),
    "blaziken": SpeciesInfo(257, "Blaziken", "fire", "fighting", BaseStats(240, 141, 190)),
    "swampert": SpeciesInfo(260, "Swampert", "water", "ground", BaseStats(208, 175, 225)),
    "mightyena": SpeciesInfo(262, "Mightyena", "dark", None, BaseStats(171, 132, 172)),
    "slaking": SpeciesInfo(289, "Slaking", "normal", None, BaseStats(319, 166, 284)),
    "ninjask": SpeciesInfo(291, "Ninjask", "bug", "flying", BaseStats(160, 133, 156)),
    "shedinja": SpeciesInfo(292, "Shedinja", "bug", "ghost", BaseStats(153, 73, 1)),
    "aggron": SpeciesInfo(306, "Aggron", "steel", "rock", BaseStats(198, 257, 172)),
    "medicham": SpeciesInfo(308, "Medicham", "fighting", "psychic", BaseStats(121, 152, 155)),
    "manectric": SpeciesInfo(310, "Manectric", "electric", None, BaseStats(215, 127, 172)),
    "plusle": SpeciesInfo(311, "Plusle", "electric", None, BaseStats(167, 129, 155)),
    "minun": SpeciesInfo(312, "Minun", "electric", None, BaseStats(147, 136, 155)),
    "volbeat": SpeciesInfo(313, "Volbeat", "bug", None, BaseStats(143, 166, 163)),
    "illumise": SpeciesInfo(314, "Illumise", "bug", None, BaseStats(143, 166, 163)),
    "roserade": SpeciesInfo(407, "Roserade", "grass", "poison", BaseStats(243, 185, 155)),
    "rampardos": SpeciesInfo(409, "Rampardos", "rock", None, BaseStats(295, 109, 219)),
    "bastiodon": SpeciesInfo(411, "Bastiodon", "rock", "steel", BaseStats(94, 286, 155)),
    "luxray": SpeciesInfo(405, "Luxray", "electric", None, BaseStats(232, 156, 190)),
    "floatzel": SpeciesInfo(419, "Floatzel", "water", None, BaseStats(221, 114, 198)),
    "honchkrow": SpeciesInfo(430, "Honchkrow", "dark", "flying", BaseStats(243, 103, 225)),
    "magnezone": SpeciesInfo(462, "Magnezone", "electric", "steel", BaseStats(238, 205, 172)),
    "rhyperior": SpeciesInfo(464, "Rhyperior", "ground", "rock", BaseStats(241, 190, 251)),
    "electivire": SpeciesInfo(466, "Electivire", "electric", None, BaseStats(249, 163, 181)),
    "magmortar": SpeciesInfo(467, "Magmortar", "fire", None, BaseStats(247, 172, 181)),
    "leafeon": SpeciesInfo(470, "Leafeon", "grass", None, BaseStats(216, 219, 163)),
    "glaceon": SpeciesInfo(471, "Glaceon", "ice", None, BaseStats(238, 205, 163)),
    "gliscor": SpeciesInfo(472, "Gliscor", "ground", "flying", BaseStats(185, 184, 181)),
    "mamoswine": SpeciesInfo(473, "Mamoswine", "ice", "ground", BaseStats(247, 146, 242)),
    "porygon_z": SpeciesInfo(474, "Porygon-Z", "normal", None, BaseStats(264, 150, 198)),
    "gallade": SpeciesInfo(475, "Gallade", "psychic", "fighting", BaseStats(237, 218, 169)),
    "probopass": SpeciesInfo(476, "Probopass", "rock", "steel", BaseStats(135, 273, 155)),
    "dusknoir": SpeciesInfo(477, "Dusknoir", "ghost", None, BaseStats(180, 254, 144)),
    "froslass": SpeciesInfo(478, "Froslass", "ice", "ghost", BaseStats(171, 150, 172)),
    "rotom": SpeciesInfo(479, "Rotom", "electric", "ghost", BaseStats(185, 159, 137)),
    "dialga": SpeciesInfo(483, "Dialga", "steel", "dragon", BaseStats(275, 211, 205)),
    "palkia": SpeciesInfo(484, "Palkia", "water", "dragon", BaseStats(280, 215, 189)),
    "heatran": SpeciesInfo(485, "Heatran", "fire", "steel", BaseStats(251, 213, 209)),
    "regigigas": SpeciesInfo(486, "Regigigas", "normal", None, BaseStats(287, 210, 221)),
    "giratina_altered": SpeciesInfo(
        487, "Giratina (Altered)", "ghost", "dragon", BaseStats(187, 225, 284)
    ),
    "giratina_origin": SpeciesInfo(
        487, "Giratina (Origin)", "ghost", "dragon", BaseStats(225, 187, 284)
    ),
    "cresselia": SpeciesInfo(488, "Cresselia", "psychic", None, BaseStats(152, 258, 260)),
    "darkrai": SpeciesInfo(491, "Darkrai", "dark", None, BaseStats(285, 162, 172)),
    "manaphy": SpeciesInfo(490, "Manaphy", "water", None, BaseStats(210, 210, 225)),
    "shaymin_sky": SpeciesInfo(492, "Shaymin (Sky)", "grass", "flying", BaseStats(261, 166, 225)),
    "arceus": SpeciesInfo(493, "Arceus", "normal", None, BaseStats(238, 238, 237)),
    "victini": SpeciesInfo(494, "Victini", "psychic", "fire", BaseStats(210, 210, 225)),
    "snivy": SpeciesInfo(495, "Snivy", "grass", None, BaseStats(88, 107, 128)),
    "servine": SpeciesInfo(496, "Servine", "grass", None, BaseStats(122, 155, 155)),
    "serperior": SpeciesInfo(497, "Serperior", "grass", None, BaseStats(161, 204, 181)),
    "tepig": SpeciesInfo(498, "Tepig", "fire", None, BaseStats(115, 85, 163)),
    "pignite": SpeciesInfo(499, "Pignite", "fire", "fighting", BaseStats(173, 106, 207)),
    "samurott": SpeciesInfo(503, "Samurott", "water", None, BaseStats(212, 212, 216)),
    "stoutland": SpeciesInfo(508, "Stoutland", "normal", None, BaseStats(206, 182, 198)),
    "gigalith": SpeciesInfo(526, "Gigalith", "rock", None, BaseStats(226, 201, 198)),
    "excadrill": SpeciesInfo(530, "Excadrill", "ground", "steel", BaseStats(255, 129, 242)),
    "conkeldurr": SpeciesInfo(534, "Conkeldurr", "fighting", None, BaseStats(243, 158, 233)),
    "seismitoad": SpeciesInfo(537, "Seismitoad", "water", "ground", BaseStats(188, 150, 233)),
    "leavanny": SpeciesInfo(542, "Leavanny", "bug", "grass", BaseStats(205, 145, 181)),
    "scolipede": SpeciesInfo(545, "Scolipede", "bug", "poison", BaseStats(175, 159, 155)),
    "whimsicott": SpeciesInfo(547, "Whimsicott", "grass", "fairy", BaseStats(164, 176, 155)),
    "lilligant": SpeciesInfo(549, "Lilligant", "grass", None, BaseStats(214, 155, 172)),
    "basculin": SpeciesInfo(550, "Basculin", "water", None, BaseStats(189, 129, 172)),
    "krookodile": SpeciesInfo(553, "Krookodile", "ground", "dark", BaseStats(229, 163, 216)),
    "darmanitan": SpeciesInfo(555, "Darmanitan", "fire", None, BaseStats(263, 114, 233)),
    "scrafty": SpeciesInfo(560, "Scrafty", "dark", "fighting", BaseStats(163, 205, 163)),
    "cofagrigus": SpeciesInfo(563, "Cofagrigus", "ghost", None, BaseStats(163, 237, 154)),
    "carracosta": SpeciesInfo(565, "Carracosta", "water", "rock", BaseStats(170, 200, 179)),
    "archeops": SpeciesInfo(567, "Archeops", "rock", "flying", BaseStats(292, 139, 181)),
    "garbodor": SpeciesInfo(569, "Garbodor", "poison", None, BaseStats(181, 164, 190)),
    "zoroark": SpeciesInfo(571, "Zoroark", "dark", None, BaseStats(250, 127, 155)),
    "chandelure": SpeciesInfo(609, "Chandelure", "ghost", "fire", BaseStats(271, 182, 155)),
    "haxorus": SpeciesInfo(612, "Haxorus", "dragon", None, BaseStats(284, 183, 183)),
    "beartic": SpeciesInfo(614, "Beartic", "ice", None, BaseStats(233, 152, 216)),
    "cryogonal": SpeciesInfo(615, "Cryogonal", "ice", None, BaseStats(190, 169, 190)),
    "mienshao": SpeciesInfo(620, "Mienshao", "fighting", None, BaseStats(258, 127, 163)),
    "druddigon": SpeciesInfo(621, "Druddigon", "dragon", None, BaseStats(213, 170, 191)),
    "golurk": SpeciesInfo(623, "Golurk", "ground", "ghost", BaseStats(222, 154, 205)),
    "bisharp": SpeciesInfo(625, "Bisharp", "dark", "steel", BaseStats(232, 176, 163)),
    "braviary": SpeciesInfo(628, "Braviary", "normal", "flying", BaseStats(232, 152, 225)),
    "mandibuzz": SpeciesInfo(630, "Mandibuzz", "dark", "flying", BaseStats(129, 210, 242)),
    "heatmor": SpeciesInfo(631, "Heatmor", "fire", None, BaseStats(203, 152, 198)),
    "durant": SpeciesInfo(632, "Durant", "bug", "steel", BaseStats(217, 188, 154)),
    "deino": SpeciesInfo(633, "Deino", "dark", "dragon", BaseStats(116, 93, 141)),
    "zweilous": SpeciesInfo(634, "Zweilous", "dark", "dragon", BaseStats(159, 135, 162)),
    "hydreigon": SpeciesInfo(635, "Hydreigon", "dark", "dragon", BaseStats(256, 188, 211)),
    "volcarona": SpeciesInfo(637, "Volcarona", "bug", "fire", BaseStats(264, 189, 198)),
    "cobalion": SpeciesInfo(638, "Cobalion", "steel", "fighting", BaseStats(192, 229, 209)),
    "terrakion": SpeciesInfo(639, "Terrakion", "rock", "fighting", BaseStats(260, 192, 209)),
    "virizion": SpeciesInfo(640, "Virizion", "grass", "fighting", BaseStats(192, 229, 209)),
    "tornadus": SpeciesInfo(641, "Tornadus", "flying", None, BaseStats(266, 148, 188)),
    "thundurus": SpeciesInfo(642, "Thundurus", "electric", "flying", BaseStats(266, 146, 188)),
    "landorus_therian": SpeciesInfo(
        645, "Landorus (Therian)", "ground", "flying", BaseStats(289, 179, 205)
    ),
    "kyurem": SpeciesInfo(646, "Kyurem", "dragon", "ice", BaseStats(270, 212, 245)),
    "keldeo": SpeciesInfo(647, "Keldeo", "water", "fighting", BaseStats(260, 175, 209)),
    "meloetta_aria": SpeciesInfo(
        648, "Meloetta (Aria)", "normal", "psychic", BaseStats(250, 185, 225)
    ),
    "genesect": SpeciesInfo(649, "Genesect", "bug", "steel", BaseStats(252, 198, 174)),
    "reshiram": SpeciesInfo(643, "Reshiram", "dragon", "fire", BaseStats(275, 211, 205)),
    "zekrom": SpeciesInfo(644, "Zekrom", "dragon", "electric", BaseStats(275, 211, 205)),
    "landorus_incarnate": SpeciesInfo(
        645, "Landorus (Incarnate)", "ground", "flying", BaseStats(261, 182, 205)
    ),
    "kyogre": SpeciesInfo(382, "Kyogre", "water", None, BaseStats(270, 228, 205)),
    "groudon": SpeciesInfo(383, "Groudon", "ground", None, BaseStats(270, 228, 205)),
    "rayquaza": SpeciesInfo(384, "Rayquaza", "dragon", "flying", BaseStats(284, 170, 213)),
    "deoxys_attack": SpeciesInfo(386, "Deoxys (Attack)", "psychic", None, BaseStats(414, 46, 137)),
    "jirachi": SpeciesInfo(385, "Jirachi", "steel", "psychic", BaseStats(210, 210, 225)),
    "garchomp": SpeciesInfo(445, "Garchomp", "dragon", "ground", BaseStats(261, 193, 239)),
    "lucario": SpeciesInfo(448, "Lucario", "fighting", "steel", BaseStats(236, 144, 172)),
}

# Helper: list all distinct types
ALL_TYPES: list[str] = [t.value for t in PokemonType]

# Alias for backwards compat (tests import EFFECTIVENESS)
EFFECTIVENESS: dict[tuple[str, str], float] = TYPE_EFFECTIVENESS


# Helper: type effectiveness lookup with fallback to 1.0
def type_multiplier(attack_type: str, defender_type1: str, defender_type2: str | None) -> float:
    """Multiplicador de tipo combinado (ataque vs defensor con 1-2 tipos)."""
    m = 1.0
    m *= TYPE_EFFECTIVENESS.get((attack_type, defender_type1), 1.0)
    if defender_type2:
        m *= TYPE_EFFECTIVENESS.get((attack_type, defender_type2), 1.0)
    return m
