# Generated by Django 5.2.16 on 2026-07-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analysis", "0003_add_run_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=64, unique=True)),
                ("version", models.CharField(max_length=16)),
                ("condition_spec", models.JSONField(default=dict)),
                ("message_key", models.CharField(max_length=128)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informativo"),
                            ("warning", "Advertencia"),
                            ("critical", "Crítico"),
                        ],
                        default="info",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "regla de decisión",
                "verbose_name_plural": "reglas de decisión",
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="DecisionRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("params", models.JSONField(default=dict)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="analysis.analysisrun",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="decisions.decisionrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "recomendación",
                "verbose_name_plural": "recomendaciones",
                "ordering": ("-created_at",),
            },
        ),
    ]
