# Generated by Django 5.2.16 on 2026-07-16 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mechanics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("mechanics", "Mecánica"),
                            ("guide", "Guía"),
                            ("methodology", "Metodología"),
                            ("legal", "Legal"),
                            ("landing", "Portada"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicado"),
                            ("archived", "Archivado"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("review_date", models.DateTimeField(blank=True, null=True)),
                (
                    "mechanic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_pages",
                        to="mechanics.mechanic",
                    ),
                ),
            ],
            options={
                "verbose_name": "página de contenido",
                "verbose_name_plural": "páginas de contenido",
            },
        ),
        migrations.CreateModel(
            name="ContentPageTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locale", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=256)),
                ("body", models.TextField(help_text="Contenido renderizable (HTML)")),
                ("seo_title", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "seo_description",
                    models.CharField(blank=True, max_length=320, null=True),
                ),
                ("og_fields", models.JSONField(blank=True, default=dict)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="content.contentpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "traducción de página",
                "verbose_name_plural": "traducciones de página",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("page", "locale"), name="uq_content_page_translation"
                    )
                ],
            },
        ),
    ]
