# Generated by Django 5.2.16 on 2026-07-17 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "ruleset_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "algorithm_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("method_params", models.JSONField(blank=True, default=dict)),
                ("random_seed", models.IntegerField(blank=True, null=True)),
                ("code_sha", models.CharField(blank=True, default="", max_length=64)),
                ("mixing_flags", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ejecución de análisis",
                "verbose_name_plural": "ejecuciones de análisis",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metric_key", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="analysis.analysisrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "resultado de análisis",
                "verbose_name_plural": "resultados de análisis",
                "ordering": ("metric_key",),
            },
        ),
    ]
