# Generated by Django 5.2.16 on 2026-07-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="input_fingerprint",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
    ]
