# Generated by Django 5.2.16 on 2026-07-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_analysisrun_input_fingerprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("complete", "Completado"),
                    ("failed", "Fallido"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
