# Generated by Django 5.2.16 on 2026-07-17 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mechanics", "0002_mechanic_current_ruleset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "default_friendship",
                    models.CharField(
                        choices=[
                            ("good", "Good Friends"),
                            ("great", "Great Friends"),
                            ("ultra", "Ultra Friends"),
                            ("best", "Best Friends"),
                        ],
                        default="good",
                        max_length=16,
                    ),
                ),
                (
                    "default_trade_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("lucky", "Lucky"),
                            ("lucky_guaranteed", "Lucky garantizado"),
                        ],
                        default="normal",
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "sesión de intercambios",
                "verbose_name_plural": "sesiones de intercambios",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="TradeObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("observed_at", models.DateTimeField()),
                ("tz_offset", models.IntegerField(blank=True, null=True)),
                (
                    "friendship_level",
                    models.CharField(
                        choices=[
                            ("good", "Good Friends"),
                            ("great", "Great Friends"),
                            ("ultra", "Ultra Friends"),
                            ("best", "Best Friends"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("lucky", "Lucky"),
                            ("lucky_guaranteed", "Lucky garantizado"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "is_lucky",
                    models.BooleanField(
                        default=False,
                        help_text="DERIVADO: True si trade_type es lucky o lucky_guaranteed",
                    ),
                ),
                ("lucky_guaranteed", models.BooleanField(blank=True, null=True)),
                ("atk", models.IntegerField()),
                ("iv_def", models.IntegerField(db_column="def", verbose_name="Def")),
                ("hp", models.IntegerField()),
                ("species", models.CharField(blank=True, default="", max_length=128)),
                ("special_trade", models.BooleanField(blank=True, null=True)),
                (
                    "oldest_age_bucket",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "event_context",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "app_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "input_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("batch", "Por lotes"),
                            ("csv", "CSV"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("valid", "Válido"),
                            ("excluded", "Excluido"),
                            ("suspicious", "Sospechoso"),
                            ("duplicate", "Duplicado"),
                            ("deleted", "Eliminado"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("exclusion_reason", models.TextField(blank=True, default="")),
                ("contribution_optin", models.BooleanField(default=False)),
                (
                    "dedup_hash",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_observations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ruleset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="observations",
                        to="mechanics.mechanicruleset",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="trades.tradesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "observación de intercambio",
                "verbose_name_plural": "observaciones de intercambios",
                "indexes": [
                    models.Index(
                        fields=["owner", "is_lucky", "ruleset", "observed_at"],
                        name="trade_obs_owner_lucky_ruleset",
                    ),
                    models.Index(fields=["dedup_hash"], name="trade_obs_dedup_hash"),
                ],
            },
        ),
    ]
