# Generated by Django 5.2.16 on 2026-07-19 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mechanics", "0002_mechanic_current_ruleset"),
        ("trades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tradeobservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedup_hash__gt", ""))
                & ~models.Q(("state__in", ("duplicate", "deleted"))),
                fields=("owner", "dedup_hash"),
                name="uq_trade_observation_owner_dedup",
            ),
        ),
    ]
