# Generated by Django 5.2.16 on 2026-07-16 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mechanics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("url", models.URLField(blank=True, max_length=512, null=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("oficial", "Oficial"),
                            ("community_research", "Investigación comunitaria"),
                            ("datamining", "Datamining"),
                            ("inference", "Inferencia"),
                            ("internal_hypothesis", "Hipótesis interna"),
                        ],
                        max_length=32,
                    ),
                ),
                ("author_org", models.CharField(blank=True, max_length=128, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("retrieved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("vigente", "Vigente"),
                            ("en_revision", "En revisión"),
                            ("obsoleta", "Obsoleta"),
                            ("contradicha", "Contradicha"),
                        ],
                        default="vigente",
                        max_length=32,
                    ),
                ),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "referencia de fuente",
                "verbose_name_plural": "referencias de fuente",
                "indexes": [
                    models.Index(fields=["source_type"], name="sources_sou_source__a41e7e_idx"),
                    models.Index(fields=["status"], name="sources_sou_status_8016f5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scope", models.CharField(blank=True, max_length=128, null=True)),
                ("quote_summary", models.TextField(blank=True, null=True)),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("high", "Alto"),
                            ("medium", "Medio"),
                            ("low", "Bajo"),
                            ("hypothetical", "Hipotético"),
                        ],
                        default="medium",
                        max_length=32,
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claims",
                        to="mechanics.ruleparameter",
                    ),
                ),
                (
                    "ruleset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claims",
                        to="mechanics.mechanicruleset",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="sources.sourcereference",
                    ),
                ),
            ],
            options={
                "verbose_name": "afirmación citada",
                "verbose_name_plural": "afirmaciones citadas",
                "indexes": [
                    models.Index(fields=["source"], name="sources_sou_source__0b01da_idx"),
                    models.Index(fields=["ruleset"], name="sources_sou_ruleset_469d7b_idx"),
                    models.Index(fields=["parameter"], name="sources_sou_paramet_bebf43_idx"),
                ],
            },
        ),
    ]
