# Generated by Django 5.2.16 on 2026-07-16 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mechanic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "key",
                    models.CharField(
                        help_text="Código interno, ej. trade_iv",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("deprecated", "Deprecada"),
                            ("experimental", "Experimental"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "mecánica",
                "verbose_name_plural": "mecánicas",
                "ordering": ("sort_order", "slug"),
            },
        ),
        migrations.CreateModel(
            name="MechanicRuleSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField()),
                ("name", models.CharField(max_length=128)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "confidence_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "Alto"),
                            ("medium", "Medio"),
                            ("low", "Bajo"),
                            ("hypothetical", "Hipotético"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "mechanic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rulesets",
                        to="mechanics.mechanic",
                    ),
                ),
            ],
            options={
                "verbose_name": "ruleset",
                "verbose_name_plural": "rulesets",
                "ordering": ("-version",),
            },
        ),
        migrations.CreateModel(
            name="RuleParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=64)),
                ("value", models.JSONField()),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("integer", "Entero"),
                            ("float", "Decimal"),
                            ("boolean", "Booleano"),
                            ("string", "Texto"),
                            ("json", "JSON"),
                        ],
                        default="integer",
                        max_length=32,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="mechanics.mechanicruleset",
                    ),
                ),
            ],
            options={
                "verbose_name": "parámetro de ruleset",
                "verbose_name_plural": "parámetros de ruleset",
            },
        ),
        migrations.AddIndex(
            model_name="mechanicruleset",
            index=models.Index(fields=["effective_from"], name="mechanics_m_effecti_f30f9d_idx"),
        ),
        migrations.AddIndex(
            model_name="mechanicruleset",
            index=models.Index(fields=["effective_to"], name="mechanics_m_effecti_ecc27f_idx"),
        ),
        migrations.AddConstraint(
            model_name="mechanicruleset",
            constraint=models.UniqueConstraint(
                fields=("mechanic", "version"), name="uq_ruleset_mechanic_version"
            ),
        ),
        migrations.AddIndex(
            model_name="ruleparameter",
            index=models.Index(fields=["key"], name="mechanics_r_key_951934_idx"),
        ),
    ]
