# Generated by Django 5.2.16 on 2026-07-16 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mechanics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanic",
            name="current_ruleset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mechanics.mechanicruleset",
            ),
        ),
    ]
